version: '3'
services:
  
  orbits-game:
    container_name: "orbits-nginx-entry"
    image:          "orbits-nginx-entry"
    ports:
      - "5000:80"
    volumes:
      - ./src:/srv
  
  log-server:
    container_name: "orbits-log-server"
    image:          "orbits-laravel-entry"
    ports:
      - "5002:80"
    volumes:
      - ./src/log-server:/srv

  config-server:
    container_name: "orbits-config-server"
    image:          "orbits-laravel-entry"
    ports:
      - "5001:80"
    volumes:
      - ./src/config-server:/srv

  orbits-pgsql:
    container_name: "orbits-pgsql"
    image:          "orbits-pgsql"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./db:/srv
