version: '3'
services:
  
  orbits-app:
    container_name: "orbits-nginx-entry"
    image:          "orbits-nginx-entry"
    ports:
      - "5000:80"
    volumes:
      - ./src:/srv
  
  config-server:
    container_name: "config-server"
    image:          "orbits-php-entry"
    ports:
      - "5001:80"
    volumes:
      - ./src/config-server:/srv

    nodejs-server:
      container_name: "nodejs-server"
      image:          "orbits-base-nodejs"
