version: '3'
services:
  
  log-server:
    container_name: "orbits-log-server"
    image:          "orbits-php-entry"
    ports:
      - "5002:80"
    volumes:
      - ./src/log-server:/srv

  config-server:
    container_name: "orbits-config-server"
    image:          "orbits-php-entry"
    ports:
      - "5001:80"
    volumes:
      - ./src/config-server:/srv

  orbits-game:
    container_name: "orbits-nginx-entry"
    image:          "orbits-nginx-entry"
    ports:
      - "5000:80"
    volumes:
      - ./src:/srv
  


  # nodejs-server:
  #   container_name: "orbits-nodejs-server"
  #   image:          "orbits-base-nodejs"
